plugins:
  - uglifier
markdown: PandocProcessor
exclude: [Gemfile, Gemfile.lock]
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  startings: [html, head, body]
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
