markdown: PandocProcessor
pandoc:
  default_image_extension: "svg"
exclude: [Gemfile, Gemfile.lock]
defaults:
  - scope:
      path: "*.md"
    values:
      layout: "default"
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  startings: [html, head, body]
sass:
  style: compressed
  sourcemap: never
