name: Build test page

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-test.yml"
      - "test/**"
      - "www/**"
      - "Dockerfile"
      - "action.yml"
      - "main.sh"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          perl -pi -e "s/image: .*$/image: 'Dockerfile'/g" action.yml
          cat action.yml
      - uses: ./
        with:
          setupscript: |
            cp test/index.md /www/
            cp -r test/figures /www/
            cp -r test/_sections /www/_includes/sections
            cp -r test/_utils /www/_includes/utils
            cp test/_references.bib /www/_includes/references.bib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
