name: Build test page

on:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        perl -pi -e "s/image: .*$/image: 'Dockerfile'/g" action.yml
        cat action.yml
    - uses: ./
      with:
        setupscript: |
          cp test/index.md /www/
          cp -r test/figures /www/
          cp test/_includes/appendix1.md /www/_includes/
          cp test/_includes/appendix2.md /www/_includes/
          cp test/_includes/references.bib /www/_includes/
          cp test/_includes/commands.md /www/_includes/
          cp test/_includes/ext.md /www/_includes/
          cp test/_includes/local.scss /www/_includes/
          cp test/_includes/local.js /www/_includes/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
