name: Build test page

on:
  push:
    branches:
    - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        setupscript: |
          cp test/index.md /www/
          cp test/references.bib /www/_includes/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
