name: Publish assets

on:
  push:
    branches:
    - master
    paths:
    - 'assets/*'
    - 'www/*'
    - 'Dockerfile'
    - 'action.yml'
    - 'main.sh'
    - '.github/workflows/dist-assets-workflow.yml'
  workflow_run:
    workflows: ['Publish source image']
    branches:
    - master
    types:
    - completed

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        setupscript: sh .github/utils/setup.sh
        targetbranch: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
