name: Publish Docker image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - id: vars
        run: |
          echo tag=${GITHUB_REF#refs/*/} >> ${GITHUB_OUTPUT}
          echo taghead=${GITHUB_REF#refs/*/} | cut -d. -f1 >> ${GITHUB_OUTPUT}
      - uses: docker/login-action@v2
        with:
          username: jayanthkoushik
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: jayanthkoushik/paje:${{ steps.vars.outputs.tag }},jayanthkoushik/paje:${{ steps.vars.outputs.taghead }},jayanthkoushik/paje:latest
