name: Publish Docker image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - id: vars
      run: |
        echo name=tag::${GITHUB_REF#refs/*/} >> ${GITHUB_OUTPUT}
        echo name=taghead::${GITHUB_REF#refs/*/} | cut -d. -f1 >> ${GITHUB_OUTPUT}
    - uses: docker/login-action@v1
      with:
        username: jayanthkoushik
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: jayanthkoushik/paje:${{ steps.vars.outputs.tag }},jayanthkoushik/paje:${{ steps.vars.outputs.taghead }},jayanthkoushik/paje:latest
